name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, ubuntu-latest ]
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    container: ${{ matrix.os == 'ubuntu-latest' && 'swift:5.9' || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          apt-get update
          apt-get install -y --no-install-recommends make gcc binutils ca-certificates

      - name: Build
        run: make -j2

      - name: Symbols
        run: make symbols || true

      - name: Run C tests
        run: make test


